name: assesment_task
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2  
  #Svg picture
  flutter_svg: ^2.0.9
  #router
  go_router: ^13.1.0
#otp fields
  flutter_otp_text_field: ^1.1.1
  #bloc and equatable
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  #bottoomNavBar
  #salomon_bottom_bar: ^3.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

# this gives us access to all image instead of specifying them one by one
  assets:
    - assets/images/
    - assets/icons/
  # uses two types of fonts, Nexa and Birds of Paradise, both families are mentioned below
  fonts:
    - family: Nexa
      fonts:
        - asset: assets/fonts/Nexa/Nexa-Bold.otf
          weight: 700
        - asset: assets/fonts/Nexa/Nexa-Regular.otf
          weight: 500
        - asset: assets/fonts/Nexa/Nexa-Light.otf
          weight: 300 

    - family: BirdsOfParadise
      fonts:
        - asset: assets/fonts/BirdsofParadise/B-OF-Paradise.ttf
          weight: 700
          style: italic
       